### ISSUE TITLE
Can't get to run on linux or windows. 

### ISSUE THREAD

**Issue by meguminnet** [MyK00L/tategakifont#1]
Probably doing something wrong but I can't figure what:

In **Windows** after installing fontforge and python3 I get:

> Internal Error: Invalid 2nd order spline in SplineRefigure2
> Internal Error: Invalid 2nd order spline in SplineRefigure2
> Internal Error: Invalid 2nd order spline in SplineRefigure2
> Internal Error: Invalid 2nd order spline in SplineRefigure2
> Internal Error: Invalid 2nd order spline in SplineRefigure2
> Internal Error: Invalid 2nd order spline in SplineRefigure2
> Internal Error: Invalid 2nd order spline in SplineRefigure2
> Internal Error: Invalid 2nd order spline in SplineRefigure2

In **Linux** with fontforge and the python3 plugin I get:

Aside from this that are probably normal warnings:

```
No glyph with unicode U+0792a in font
No glyph with unicode U+0797f in font
No glyph with unicode U+079ae in font

```

```
Traceback (most recent call last):
  File "/home/ubuntu/fonts/tategakifont-master/main.py", line 97, in <module>
    main()
  File "/home/ubuntu/fonts/tategakifont-master/main.py", line 91, in main
    font.transform(rotcen,("round"))
TypeError: function takes exactly 1 argument (2 given)
```
The font I'm trying to rotate is [Noto Sans JP](https://fonts.google.com/noto/specimen/Noto+Sans+JP)

Thanks in advance and sorry if I overlooked something.

**Comment by meguminnet** [comment]
Pull Request #2 

Should fix this unless I missed something

**Comment by MyK00L** [comment]
@meguminnet I could not reproduce this, in the fontforge [documentation](https://fontforge.org/docs/scripting/python/fontforge.html#fontforge.font) the function accepts the second argument.
I also find it weird that in your version it does not accept it in `font.transform` but has no problem in `glyph.transform`. What fontforge version are you using?

I'll accept the PR since I don't even know if rounding is good practice or not anyway.

ps
Other than all the warnings, I noticed that the output file is smaller than the input file, which I find weird, is it the same for you?

**Comment by meguminnet** [comment]
> What fontforge version are you using?

Seems like a fairly old version of fontforge despite installing it recently.
Maybe is because of that?

```
Version: 20201107
Based on sources from 2022-01-13 19:13 UTC-ML-D-GDK3.
PythonUI_Init()
copyUIMethodsToBaseTable()
fontforge 20201107
build date: 2022-01-13 19:13 UTC
```

>  Other than all the warnings, I noticed that the output file is smaller than the input file, which I find weird, is it the same for you?

It's actually the other way for me.

Used Noto Sans Japanese Regular
- Original size in bytes: 5.732.884
- Rotated version size in bytes: 5.945.296

**Comment by MyK00L** [comment]
Thank you, with a newer version that function should probably be fine.
I changed how rounding is done anyway, so it should not be a problem even with old versions.
The font decreasing in size was for the "variable font weight" file, I might look into that later.
