### ISSUE TITLE
Cannot Create TTC font

### ISSUE THREAD

**Issue by rukit24** [MyK00L/tategakifont#6]
![image](https://github.com/MyK00L/tategakifont/assets/106027634/88bedbe3-096e-4166-b27e-27bd83597332)
Hi now i am apply your code to create rotated font. and it return error like this.  I am turn the font from ttc to ttf. My resource Font is here https://eng.m.fontke.com/font/87360514/download/

**Comment by MyK00L** [comment]
My bad, the README was wrong :) the correct way to start the script is: `python main.py input output` (assuming `main.py` is in the same folder).
That said, I'm not sure if this script can handle a ttc, you might want to convert (extract?) it to ttf or otf first.

**Comment by rukit24** [comment]
![image](https://github.com/MyK00L/tategakifont/assets/106027634/22e4186c-5b48-4b2a-8750-988ba04587ea)
I am look like a noobs in Tech but i do as you said it doesn't work :(
Last time i use this code it work but i think this doesn't the right way you mention: 
fontforge -lang=py -script main.py KleeOne-Regular.ttf KleeOne-Regular123.ttf

**Comment by rukit24** [comment]
Okay then i figured it out. I should use FFpython instead to apply import fontforge module. But then i got on this error due to the scripts. Can you Know why: 
![image](https://github.com/MyK00L/tategakifont/assets/106027634/671a66b3-04d7-466b-954b-2ea824fb0d5e)

**Comment by MyK00L** [comment]
Try again with the latest version, I fixed that error

**Comment by rukit24** [comment]
![image](https://github.com/MyK00L/tategakifont/assets/106027634/9ad573b2-622e-43a3-ae17-6270fa630c8f)
New error. I think it same as previous issue i provide. Maybe otf font doesn't work

**Comment by MyK00L** [comment]
Thank you, should be fixed now!

**Comment by rukit24** [comment]
It work great now. Thanks
